[package]
name = "milena-pajor-support"
version = "0.1.0"
description = "Strona wsparcia dla Mileny Pajor"

[[module]]
name = "static-site"
source = "staticfile"
abi = "none"

[module.filesystem]
"/" = "."

[command]
name = "serve"
module = "static-site"

[[command.annotations.wasi]]
main-args = ["/index.html"]